// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_codes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace StateSync.Shared {

  /// <summary>Holder for reflection information generated from error_codes.proto</summary>
  public static partial class ErrorCodesReflection {

    #region Descriptor
    /// <summary>File descriptor for error_codes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFlcnJvcl9jb2Rlcy5wcm90byqxAQoJRXJyb3JDb2RlEgsKB1NVQ0NFU1MQ",
            "ABISCg5ST09NX05PVF9GT1VORBBkEg0KCVJPT01fRlVMTBBlEhcKE1JPT01f",
            "QUxSRUFEWV9KT0lORUQQZhIXChNJTlZBTElEX01BWF9QTEFZRVJTEGcSFwoS",
            "UExBWUVSX05PVF9JTl9ST09NEMgBEhUKEEdBTUVfTk9UX1NUQVJURUQQrAIS",
            "EgoNSU5WQUxJRF9JTlBVVBCtAkITqgIQU3RhdGVTeW5jLlNoYXJlZGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::StateSync.Shared.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    [pbr::OriginalName("ROOM_NOT_FOUND")] RoomNotFound = 100,
    [pbr::OriginalName("ROOM_FULL")] RoomFull = 101,
    [pbr::OriginalName("ROOM_ALREADY_JOINED")] RoomAlreadyJoined = 102,
    [pbr::OriginalName("INVALID_MAX_PLAYERS")] InvalidMaxPlayers = 103,
    [pbr::OriginalName("PLAYER_NOT_IN_ROOM")] PlayerNotInRoom = 200,
    [pbr::OriginalName("GAME_NOT_STARTED")] GameNotStarted = 300,
    [pbr::OriginalName("INVALID_INPUT")] InvalidInput = 301,
  }

  #endregion

}

#endregion Designer generated code
