// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace StateSync.Shared {

  /// <summary>Holder for reflection information generated from message_type.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for message_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJtZXNzYWdlX3R5cGUucHJvdG8qzQEKC01lc3NhZ2VUeXBlEg8KC1VOU1BF",
            "Q0lGSUVEEAASDQoJSk9JTl9ST09NEAESDgoKTEVBVkVfUk9PTRACEhEKDVBM",
            "QVlFUl9KT0lORUQQAxIQCgxQTEFZRVJfSU5QVVQQBBIPCgtXT1JMRF9TVEFU",
            "RRAFEg8KC0NSRUFURV9ST09NEAYSEAoMTU9WRV9SRVFVRVNUEAcSDgoKTU9W",
            "RV9FVkVOVBAIEhEKDVBPU0lUSU9OX1NZTkMQCRIICgRQSU5HEAoSCAoEUE9O",
            "RxALQhOqAhBTdGF0ZVN5bmMuU2hhcmVkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::StateSync.Shared.MessageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("JOIN_ROOM")] JoinRoom = 1,
    [pbr::OriginalName("LEAVE_ROOM")] LeaveRoom = 2,
    [pbr::OriginalName("PLAYER_JOINED")] PlayerJoined = 3,
    [pbr::OriginalName("PLAYER_INPUT")] PlayerInput = 4,
    [pbr::OriginalName("WORLD_STATE")] WorldState = 5,
    [pbr::OriginalName("CREATE_ROOM")] CreateRoom = 6,
    [pbr::OriginalName("MOVE_REQUEST")] MoveRequest = 7,
    [pbr::OriginalName("MOVE_EVENT")] MoveEvent = 8,
    [pbr::OriginalName("POSITION_SYNC")] PositionSync = 9,
    [pbr::OriginalName("PING")] Ping = 10,
    [pbr::OriginalName("PONG")] Pong = 11,
  }

  #endregion

}

#endregion Designer generated code
